require("eze.config.plugin_config.gruvbox")
require("eze.config.plugin_config.treesitter")
require("eze.config.plugin_config.lsp-zero")
require("eze.config.plugin_config.telescope-keys")
require("eze.config.plugin_config.indent-blankline")
require("eze.config.plugin_config.lualine")
