require("eze.config.plugin_config.treesitter")
require("eze.config.plugin_config.catppuccin")
require("eze.config.plugin_config.telescope")
require("eze.config.plugin_config.nvim-web-devicons")
require("eze.config.plugin_config.indent-blankline")
